import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes'
import "../styles/globals.css";
import { IBMPlex } from "./lib/IBMPlexFont";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${IBMPlex.className} dark:bg-gray-900`}
      > 
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
